### ISSUE TITLE
APF Prod Bug fixes : Batch 4: Offline Dashboard: Mismatch in the count between the total enrolled children and the growth monitoring schedule

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#380]
- [ ] Changes to be done in APF New UAT environment
- [ ] Count Mismatch in the below two Offline Dashboard Cards related to Child Program

Dashboard - Child - Total enrolment in child program
Child Schedule and backlog visit - Growth Monitoring

| Expected Behaviour                                           | Current Behaviour                                            |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| Count of Total Child Enrolled should be equal to Number of Growth Monitoring Scheduled this month + Number of Growth Monitoring visits done this month | Count of Total Child Enrolled is not equal to Number of Growth Monitoring Scheduled this month + Number of Growth Monitoring visits done this month |

User Id :  7735569283@apfodisha, 7207486281@apfodisha, 7670853007@apfodisha, 9692184518@apfodisha
Role: Poshan Sathi

**Comment by sachsk** [comment]
This issue is related to timezone we have fixed as a part of this card :https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/385

this will get fixed once user will schedule new visit

**Comment by Dinesh2019** [comment]
As discussed with Sachin the count mismatches still exist since we had the time zone issue.
